/**
 * @description       : example class to show how affirm validates a package on push
 * @author            : drewtsnyder@gmail.com
 * @group             : 
 * @last modified on  : 05-07-2021
 * @last modified by  : drewtsnyder@gmail.com
 * Modifications Log 
 * Ver   Date         Author                            Modification
 * 1.0   05-07-2021   drewtsnyder@gmail.com             Initial Version
**/
public with sharing class MyExampleClass {
    public static String forTesting = 'MyExampleClass Test';
}
