/**
 * @description       : example class to show how affirm validates a package on push
 * @coverage          : MyExampleClassTest
 * @author            : drew.snyder@hunterdouglas.com
 * @group             : Example Code
 * @last modified on  : 01-28-2023
 * @last modified by  : drew.snyder@hunterdouglas.com
 * Modifications Log
 * Ver   Date         Author                          Modification
 * 1.0   05-07-2021   drew.snyder@hunterdouglas.com   Initial Version
 * 1.1   01-28-2023   drew.snyder@hunterdouglas.com   updated header
 **/
public with sharing class MyExampleClass {
  public static String forTesting = 'MyExampleClass Test';
}
